version: '3.8'

services:
  telegram-media-bot:
    container_name: telegram-media-bot
    build: .
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./downloads:/app/downloads
